package com.example.enums;

public enum Specialty { // shifokor mutaxasisligi

    AKUSHER,
    ALLERGOLOK,
    ANDROLOG,
    ANESTIZOLOG,
    VENEROLOG,
    VERTEBLOROG,
    VIRUSOLOG,
    GASTROENTEROLOG,
    GEMATOLOG,
    GEPATOLOG,
    GINEKOLOG,
    GIRUDOTERAPEVT,
    GEMEOPD,
    Дерматовенеролог,
    Дерматолог,
    Диетолог,
    Иглотерапевт,
    Иммунолог,
    ИФА,
    Кардиолог,
    Косметолог,
    Лаборант,
    Маммолог,
    Массажист,
    Миколог,
    МРТ,
    Нарколог,
    Невролог,
    Невропатолог,
    Нейрофизиолог,
    Нейрохирург,
    Неонатолог,
    Нефролог,
    Онколог,
    Оптика,
    Ортодонт,
    Ортопед,
    Отоларинголог,
    Офтальмолог,
    Педиатр
}
