### upload
POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="20200112_204646.jpg"

< D:\SHaxsiy narsalarim\rasm\20200112_204646.jpg
